nginx:
  image: finchcloud/nginx
  links:
   - consul
  ports:
   - 80:80

consul:
  image: progrium/consul
  command: -server -bootstrap -ui-dir /ui
  hostname: consul-node-1

service:
  image: finchcloud/nginx-dev-service
  links:
   - consul